### ISSUE TITLE
[BUG] [ws-azure-workitems-integration] incorrect parsing of project tokens from param.config

### ISSUE THREAD

**Issue by Nyxel** [whitesource-ps/ws-azure-workitems-integration#26]
**Bug Description**  
A loop likely meant to iterate of multiple project tokens takes the input as a string instead of a list/collection, causing it to iterate over single characters in the string: [Line of code in question](https://github.com/whitesource-ps/ws-azure-workitems-integration/blob/95a5a508be734222e384dba86938feeae969a6ff/ws_azure_workitems_integration/wi_integration.py#L103)

**Steps to Reproduce**  
1. Set at least 1 (valid) project token for key 'wsprojects' in params.config
2. Run the tool

**Expected Behavior**  
Tool queries Mend API with project token(s) given in config file

**Actual behaviour**  
Tool gives uses individual characters instead of the token, leading to an error when used against API later in the tool execution (API call handled by ws_sdk)

**Tool output**

> INFO 22-09-14 14:07:43 19304 Sync Run: Start running Azure Work Items Integration Version 0.0.1.1.
> INFO 22-09-14 14:07:43 19304 Sync Run: Sync process is started
> Traceback (most recent call last):
>   File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "c:\Users\mwunder\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
>     cli.main()
>   File "c:\Users\mwunder\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
>     run()
>   File "c:\Users\mwunder\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
>     runpy.run_path(target, run_name="__main__")
>   File "c:\Users\mwunder\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "c:\Users\mwunder\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "c:\Users\mwunder\.vscode\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
>     exec(code, run_globals)
>   File "c:\dev\lab\ws-azure-workitems-integration2\ws_azure_workitems_integration\wi_integration.py", line 135, in <module>
>     main()
>   File "c:\dev\lab\ws-azure-workitems-integration2\ws_azure_workitems_integration\wi_integration.py", line 54, in main
>     prepare_json_links()
>   File "c:\dev\lab\ws-azure-workitems-integration2\ws_azure_workitems_integration\wi_integration.py", line 104, in prepare_json_links
>     rt = WS.call_ws_api(self=conf.ws_conn, request_type="getProjectTags", kv_dict={"projectToken": el_prj})
>   File "c:\dev\lab\ws-azure-workitems-integration2\.venv\lib\site-packages\ws_sdk\app.py", line 232, in call_ws_api
>     __handle_ws_server_errors(resp.text)
>   File "c:\dev\lab\ws-azure-workitems-integration2\.venv\lib\site-packages\ws_sdk\app.py", line 206, in __handle_ws_server_errors
>     raise WsSdkServerGenericError(body[token], error)
> **ws_sdk.ws_errors.WsSdkServerGenericError: Generic error on token: '2'. Error: {"errorCode":1004,"errorMessage":"Invalid project token"}**

**Environment Details**  
 - ws-azure-workitems-integration commit 95a5a508be734222e384dba86938feeae969a6ff (master at time of writing)
 - Win10 21H2
 - Python 3.10.7
 - ws-sdk package 0.9.4

**Comment by DimarrWS** [comment]
Hi @Nyxel ! I suppose we fixed it. Can you, please, reproduce this issue, if possible with the latest version of the tool? Thanks in advance!

**Comment by Nyxel** [comment]
> Hi @Nyxel ! I suppose we fixed it. Can you, please, reproduce this issue, if possible with the latest version of the tool? Thanks in advance!

Hi @DimarrWS, I am a bit confused, as I see no new commits on the master branch here and now new version of the pip package at https://pypi.org/project/ws-wi-integration/. 
Where should I take that fixed version from?
I have speculatively updated the dependency ws-sdk to version 22.8.4.2, with no effect (issue persists).

**Comment by DimarrWS** [comment]
We did not use the tag on this tool just now, because this is still under maintenance.
The version is here https://github.com/whitesource-ps/ws-azure-workitems-integration
If you use a standard pipeline on Azure it should take automatically.
